name: WelcomeOwner
main: WelcomeOwner\MainClass
version: 1.0.0
api: 1.1.0
commands:
  owner:
    usage: /owner
    description: Tells the player who the Owner is
    permission: welcomeowner.command.owner
  CoOwner:
    usage: /coowner
    description: Tells the player who the CoOwner is
    permission: welcomeowner.command.coowner
permissions:
  welcomeowner:
    default: false
    description: Allows the player to use all of the WelcomeOwner functions
    children:
      welcomeowner.command:
        default: false
        description: Allows the player to use all of the WelcomeOwner commands
        children:
          welcomeowner.command.owner:
            default: true
            description: Allows the player to run the Owner command
          welcomeowner.command.coowner:
            default: true
            description: Allows the player to run the CoOwner command
